#include "lorem_ipsum.h"


const char * lorem_ipsum_wc123 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque velit ac gravida accumsan. Duis at varius erat. Vivamus ultricies eleifend tincidunt. Pellentesque laoreet diam quis tellus convallis ornare quis in turpis. Donec tempor risus ut finibus gravida. Sed at diam rhoncus, commodo metus quis, dignissim enim. Suspendisse venenatis felis ut tellus cursus, id volutpat neque feugiat. Praesent feugiat viverra ligula, lobortis gravida leo auctor et. Vivamus egestas orci quam, vitae consectetur nibh ullamcorper id. Suspendisse laoreet dui dapibus massa lobortis, vitae consectetur erat viverra. Nunc efficitur neque sit amet odio hendrerit dictum. Integer eleifend at justo nec pharetra. Suspendisse id faucibus augue. Phasellus massa libero, aliquet et euismod sed, facilisis ac nunc. Duis pharetra, lacus vitae vestibulum ornare, sapien orci blandit lectus.";
const char* lorem_ipsum_wc2000 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id augue commodo sem suscipit gravida. Proin risus tellus, commodo at gravida in, rhoncus eu purus. Ut eu dolor nec lectus congue mattis elementum a sem. Maecenas tincidunt pretium dui. Nulla ultricies sapien ligula, ac pulvinar est mollis sit amet. Nunc sit amet urna gravida, hendrerit enim id, auctor lorem. Quisque consequat eu augue nec lacinia.\
\
Aenean tellus ipsum, fermentum non elit ac, tristique egestas quam. Nam condimentum massa viverra porttitor malesuada. In sit amet magna in magna interdum euismod quis a mi. Fusce faucibus lobortis sollicitudin. Nam velit diam, efficitur sed semper ac, consectetur sed nisi. Aliquam nec iaculis mi, sit amet aliquam lacus. Aliquam eu orci eros. Pellentesque pulvinar auctor felis vel commodo. Praesent consectetur, leo sed blandit ullamcorper, ligula velit luctus elit, ac fringilla lacus quam sed nunc.\
\
Nulla euismod dolor in pulvinar blandit. Maecenas elit lorem, finibus sed bibendum maximus, rhoncus id elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sed faucibus ligula, vel faucibus enim. Integer fringilla enim in justo tempus tempor. Curabitur eget purus posuere, tempus leo et, blandit diam. Suspendisse rhoncus tortor magna. Cras quis magna porttitor, convallis enim vitae, finibus ipsum. Nunc tincidunt, libero vel efficitur tristique, nunc justo sollicitudin ante, sit amet viverra sem lorem at enim. Etiam et convallis turpis. Duis tristique odio a eros accumsan, vehicula sagittis neque scelerisque. Phasellus blandit lacus erat, a pretium nisi accumsan faucibus. Morbi sollicitudin nunc quis risus posuere, non elementum ligula bibendum. Nullam at dolor in sem tincidunt semper.\
\
Maecenas efficitur rhoncus lorem eu vulputate. Nulla rutrum orci vitae turpis auctor tincidunt. Proin aliquam pretium felis. Proin dignissim cursus est. Pellentesque dapibus sem quis arcu dignissim, eu aliquet dui convallis. Aenean fermentum tortor eget elit varius, vitae viverra enim pellentesque. Nullam auctor iaculis volutpat. Curabitur facilisis nibh nec consectetur hendrerit. Vivamus a aliquet mauris.\
\
Praesent eu nibh nulla. Vivamus fermentum vel arcu ac lacinia. Vestibulum eget scelerisque massa. Quisque ultricies id odio et dictum. Praesent quis tortor aliquam, efficitur risus ut, iaculis magna. Ut dignissim quam eget odio ullamcorper euismod. Mauris non mi nibh. Fusce nisl sapien, mollis at magna et, cursus accumsan felis. Praesent egestas maximus ipsum nec viverra. Maecenas quis vehicula metus. Nunc et feugiat nunc. Vestibulum purus tortor, suscipit sit amet nisi sit amet, convallis fermentum augue. Suspendisse commodo dignissim tincidunt. Phasellus placerat dui vitae lorem pretium eleifend. Quisque pellentesque urna et posuere bibendum. Ut eu nibh orci.\
\
Morbi tempus vel elit vitae viverra. Vivamus id eros ante. Donec consectetur gravida bibendum. Duis commodo mauris eu erat consequat, at suscipit lacus sollicitudin. Sed pellentesque urna a molestie lobortis. Curabitur a ipsum quis elit pharetra faucibus non ut lacus. Nam ante sem, hendrerit sit amet diam ac, mattis sodales ante. Sed dignissim non libero vitae sollicitudin. Pellentesque viverra et felis et pellentesque. Nullam efficitur arcu ornare tempor ornare. Aliquam pretium at sapien et sollicitudin. Nam pretium sapien ut magna convallis, vel tempor lorem pharetra. Mauris consequat, lectus ut sodales placerat, ex libero mattis dolor, et molestie magna quam at felis.\
\
Mauris ultrices orci non egestas convallis. Sed rhoncus blandit metus, in blandit nibh finibus at. Integer id posuere metus. Cras fermentum ornare imperdiet. Cras consectetur libero ac mauris tempus porttitor. Mauris facilisis suscipit pharetra. Aliquam suscipit a orci vitae venenatis.\
\
Ut dapibus, velit sit amet bibendum ullamcorper, mauris diam volutpat orci, eget scelerisque dui magna in ipsum. Praesent gravida velit quis odio commodo tempus. Integer sed augue at ipsum ultricies feugiat ac quis libero. Morbi et magna quis eros viverra viverra nec id lectus. Nullam suscipit blandit convallis. Suspendisse velit purus, bibendum vitae risus fringilla, eleifend luctus dolor. Nulla quis turpis velit. Integer urna arcu, dapibus a dolor quis, ultricies vestibulum lorem. In at aliquet nisi, et ullamcorper neque. Etiam interdum nisl eu aliquam tincidunt.\
\
Duis vitae sagittis dui, ac ultrices nisl. Donec ac dolor et ex sodales vehicula sed non tellus. Praesent vestibulum nunc eu sapien gravida commodo. Morbi dignissim nunc sed diam sollicitudin ultricies. Sed velit felis, convallis id rhoncus vel, ullamcorper eu ante. Sed vehicula hendrerit massa, sed gravida felis. Nam pharetra augue vitae odio suscipit elementum et at lorem. Sed at ullamcorper ex.\
\
Sed condimentum elementum nibh aliquam gravida. Donec sit amet erat eu ipsum commodo finibus. Etiam et fermentum lacus. Proin accumsan tortor sed odio viverra, eget semper odio hendrerit. Donec molestie risus mi, id ultricies ligula placerat quis. Nunc suscipit turpis eu sodales iaculis. Nullam sagittis et velit eget rutrum. Praesent a aliquam leo. Donec sed arcu id tellus dictum fermentum. In tincidunt finibus leo. Vestibulum posuere risus quis nibh rutrum iaculis eu quis diam. Aliquam rutrum mauris nec massa facilisis accumsan.\
\
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce arcu tortor, consequat vitae posuere quis, vulputate non ante. Sed pretium, urna pharetra viverra venenatis, odio magna molestie ex, posuere molestie magna felis sit amet metus. Mauris viverra a leo sed mollis. Sed blandit venenatis leo, non imperdiet nulla. Phasellus sed ullamcorper felis. Donec eget velit et erat viverra iaculis. In posuere quam urna, a porta tortor condimentum ut. Maecenas at magna eu massa vestibulum rhoncus et ac odio. Ut ultrices mi eros, quis cursus lorem venenatis eget. Vivamus elit arcu, elementum id nulla non, dignissim fringilla orci. Maecenas egestas mauris eget nulla feugiat, sit amet ullamcorper urna varius. Sed semper blandit euismod. Vestibulum pellentesque eros id felis condimentum, eget tincidunt risus euismod.\
\
Proin tincidunt aliquet sem. Morbi eget orci efficitur, bibendum justo vehicula, vestibulum turpis. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus pretium metus at orci molestie, id dictum est hendrerit. Cras vestibulum turpis vel eros rutrum commodo. Aliquam cursus velit quam, a tempor purus efficitur non. Aliquam metus diam, venenatis eu posuere non, maximus in neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis hendrerit, sapien eget maximus lobortis, erat metus vulputate mauris, quis dignissim arcu leo et purus.\
\
Praesent facilisis viverra leo, nec suscipit sapien sollicitudin at. Duis at facilisis lacus. Aliquam aliquet, diam ut aliquam hendrerit, diam orci rhoncus leo, sit amet blandit nulla urna sit amet nisi. Morbi vitae erat ipsum. Aliquam feugiat consectetur augue ut pharetra. Etiam sed est sit amet lectus porta maximus quis vel metus. Mauris auctor mollis elementum. Pellentesque vel ligula et risus auctor rhoncus nec eu nibh. Integer elementum lacinia ex, sed finibus nisi maximus ut. In viverra risus orci, non consequat quam hendrerit vel. Aliquam non arcu lacus. Fusce condimentum elit ante, at posuere tortor tincidunt in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut sed arcu gravida, congue augue nec, sagittis felis. Suspendisse laoreet molestie purus, sit amet gravida felis. Suspendisse id fringilla ante.\
\
Integer porta faucibus quam, nec fringilla lacus aliquet ut. Nullam ac iaculis nisl. Fusce tempus ornare accumsan. Mauris dolor turpis, porttitor sed elit in, venenatis viverra purus. Ut convallis aliquam elit eget venenatis. Proin aliquam, purus ut laoreet ultrices, ipsum elit venenatis massa, et luctus felis felis sit amet ex. Etiam sit amet velit rhoncus nibh tristique congue vitae eu justo. Proin ullamcorper vitae erat nec vestibulum. Mauris non sem fermentum, mollis neque sit amet, egestas tortor. Nullam nec justo nisi. Nam maximus iaculis euismod. Etiam vulputate eros posuere, egestas arcu ac, mollis leo. Sed viverra, est fermentum tincidunt tincidunt, turpis mauris pulvinar nisi, at efficitur nisl nulla a leo.\
\
Etiam eleifend a magna eget dignissim. Aenean dui odio, vulputate congue enim eu, blandit dictum ipsum. Nunc elementum ligula id lorem rutrum accumsan. Cras sit amet elit a magna ullamcorper vulputate. Praesent aliquet orci massa, vel dapibus purus faucibus at. Morbi tempor rhoncus diam. Fusce eros magna, dignissim in nisl quis, euismod facilisis velit. Curabitur in risus lacus. Vivamus lacus enim, fringilla in porta id, auctor ut lectus. Praesent sit amet massa eu risus iaculis luctus. Mauris convallis sapien massa, non luctus neque luctus vitae. Fusce viverra tortor nec mi finibus, sed volutpat odio dapibus. Aenean ut elit porttitor, porta purus ut, ultricies purus. Morbi eu sem metus. Aenean luctus eros eget nunc auctor accumsan. Nunc bibendum congue tempus.\
\
Fusce mi est, vehicula at mollis ac, fringilla id nibh. Quisque eu enim odio. Morbi eget mollis nibh. Donec tristique leo sagittis posuere auctor. Vestibulum venenatis, dui ut placerat ultrices, felis diam placerat lacus, eu tincidunt ligula dolor in eros. Praesent lobortis vel odio et venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec et sem efficitur sapien aliquam scelerisque. Nam tincidunt molestie ipsum eu porta. Donec consectetur lectus turpis, sit amet efficitur justo suscipit eu. Fusce rutrum, nunc vel feugiat posuere, orci libero vehicula dui, quis facilisis ligula nisl a ex.\
\
Vivamus interdum bibendum dolor. Nullam egestas metus et bibendum consequat. Curabitur laoreet quam lorem, in eleifend elit dignissim id. Vivamus leo felis, maximus ac ligula a, iaculis sagittis magna. In eget mi ac mauris gravida gravida eget egestas mauris. Donec feugiat efficitur neque, in tincidunt tellus lacinia at. Quisque vulputate vel leo sit amet gravida. Nunc gravida, nisl quis elementum fringilla, tellus massa venenatis tortor, iaculis ornare ante odio ac nulla. In mi magna, cursus ac est sit amet, laoreet lobortis justo.\
\
Fusce viverra dictum diam, sed pellentesque dolor iaculis ac. Nullam ac sagittis arcu. Maecenas felis nunc, iaculis id venenatis vel, lacinia at lacus. Phasellus quis varius enim. Donec et tortor iaculis, varius nisi quis, rutrum risus. Aenean sagittis diam eu cursus aliquet. Morbi bibendum porttitor eleifend.\
\
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus nisi mauris, tristique sit amet pretium id, congue eu est. Vivamus vehicula ornare justo, nec rhoncus tortor commodo sed. Ut purus orci, convallis ac mauris a, lacinia dignissim risus. Sed commodo vel eros quis vestibulum. Fusce quis dolor orci. Etiam nec augue id nisl aliquam venenatis vel nec ante. Duis ullamcorper neque ac lacinia luctus. Nullam pulvinar orci at accumsan venenatis. Pellentesque ac malesuada tellus, et eleifend justo. Etiam ac velit dolor. Nam eros odio, egestas vel tellus vel, faucibus semper ipsum. Nunc in risus non nunc lacinia volutpat. Mauris gravida sapien et sem interdum scelerisque. Maecenas ullamcorper non nunc ut feugiat. Vivamus id iaculis magna.\
\
Donec pretium viverra efficitur. Curabitur commodo leo mi. Vivamus mauris dolor, egestas sit amet fermentum eu, commodo molestie velit. Phasellus vehicula semper eros, ac mattis urna pharetra quis. Integer in erat arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam suscipit, neque sit amet porta posuere, odio risus gravida massa, in hendrerit mauris mi sit amet dolor. Phasellus sollicitudin vitae felis sit amet luctus. Nulla dignissim, metus et tempor congue, nisl lectus pulvinar tellus, quis convallis purus tortor dapibus nibh. Proin tristique non felis sit amet efficitur. Duis quis eros velit. Ut quis urna ac risus eleifend pellentesque ut eu nisl.\
\
Praesent venenatis rhoncus euismod. Aliquam egestas nisl in vehicula tempus. Integer ultrices magna at consequat ultrices. Aenean ornare vulputate lobortis. Ut ornare, nisl tincidunt dignissim pellentesque, magna nisi molestie metus, non maximus est magna in magna. In convallis mi rutrum pharetra rhoncus. Nulla facilisi. Aenean porta bibendum rhoncus. Morbi porta eleifend nibh, vel fermentum risus bibendum eu. Proin vel urna sit amet est pretium pretium quis vitae leo. Nunc dapibus vel quam vitae luctus. In eget nunc blandit, imperdiet purus sit amet, bibendum erat.\
\
Quisque ac pretium odio. Quisque nisi sem, semper varius dapibus nec, blandit sed elit. Phasellus fermentum erat eu ante fringilla placerat. Morbi lobortis quam non mollis ultricies. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur vel venenatis libero. Integer sit amet facilisis neque. Vestibulum finibus velit non ex vehicula hendrerit. Donec elit tortor, pretium in lorem ut, efficitur aliquet tortor. Quisque velit nibh, viverra non sem et, pretium elementum leo. Aenean et semper dolor. Nam tempor, felis vel luctus fermentum, ipsum mauris dapibus ante, a tempor nibh quam at turpis. Proin eget magna odio. Integer tempus tortor leo, non fringilla nibh dictum posuere.";